<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8tj7I2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8tj7I2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY8tj7I2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY8tj7I2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerY8tj7I2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Y8tj7I2',
    'container.build_id' => 'f568a277',
    'container.build_time' => 1558387280,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8tj7I2');
