<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMpYPV3N\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMpYPV3N/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMpYPV3N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMpYPV3N\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMpYPV3N\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MpYPV3N',
    'container.build_id' => '39171d22',
    'container.build_time' => 1558389320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMpYPV3N');
